Repository Surcharges/Front-end, pull requests merged in 2025-02, with the labels that each got.

#82 81 fix totalamount and surchargeamount in confirmationmodal #81
  src/3_widgets/dashboard/ui/components/ConfirmationModal.tsx
  src/3_widgets/dashboard/ui/components/SurchargesList.tsx
  src/5_entities/surcharges/api/SurchargesStatusDTO.ts
Labels: bug

#85 The `AUTO_GENERATED` surcharge status is handled in Result and Place Detail pages.
  src/3_widgets/detail/api/GetPlaceDetail.ts
  src/3_widgets/detail/model/usePlaceViewModel.ts
  src/3_widgets/detail/ui/components/surchargeInformation/SurchargesDetail.tsx
  src/3_widgets/report/model/viewmodels/useReportViewModel.ts
  src/3_widgets/report/ui/Report.tsx
  src/3_widgets/results/api/GetPlaces.ts
  src/3_widgets/results/model/usePlaceListViewModel.ts
  src/3_widgets/results/ui/Results.tsx
  src/3_widgets/results/ui/placelist/PlaceItem.tsx
  src/5_entities/surcharges/model/SurchargesStatusModel.ts
  src/5_entities/surcharges/ui/SurchargesStatusUI.ts
  src/6_shared/ui/index.ts
  src/6_shared/ui/surchargeStatus/AutoGenerated.tsx
  src/6_shared/ui/surchargeStatus/help/StatusHelp.tsx
Labels: enhancement

#86 Privacy Policy has been changed #84
  src/3_widgets/privacyPolicy/ui/PrivacyPolicy.tsx
Labels: etc

#88 Added support page. #87
  src/1_app/ui/app/App.tsx
  src/3_widgets/support/index.ts
  src/3_widgets/support/ui/Support.tsx
Labels: enhancement

#89 Release
  src/1_app/ui/app/App.tsx
  src/3_widgets/dashboard/ui/components/ConfirmationModal.tsx
  src/3_widgets/dashboard/ui/components/SurchargesList.tsx
  src/3_widgets/detail/api/GetPlaceDetail.ts
  src/3_widgets/detail/model/usePlaceViewModel.ts
  src/3_widgets/detail/ui/components/surchargeInformation/SurchargesDetail.tsx
  src/3_widgets/privacyPolicy/ui/PrivacyPolicy.tsx
  src/3_widgets/report/model/viewmodels/useReportViewModel.ts
  src/3_widgets/report/ui/Report.tsx
  src/3_widgets/results/api/GetPlaces.ts
  src/3_widgets/results/model/usePlaceListViewModel.ts
  src/3_widgets/results/ui/Results.tsx
  src/3_widgets/results/ui/placelist/PlaceItem.tsx
  src/3_widgets/support/index.ts
  src/3_widgets/support/ui/Support.tsx
  src/5_entities/surcharges/api/SurchargesStatusDTO.ts
  src/5_entities/surcharges/model/SurchargesStatusModel.ts
  src/5_entities/surcharges/ui/SurchargesStatusUI.ts
  src/6_shared/ui/footer/bonsung/Bonsung.tsx
  src/6_shared/ui/footer/petr/Petr.tsx
  src/6_shared/ui/index.ts
  src/6_shared/ui/surchargeStatus/AutoGenerated.tsx
  src/6_shared/ui/surchargeStatus/help/StatusHelp.tsx
Labels: release

#90 Change support page style #87
  src/3_widgets/support/ui/Support.tsx
Labels: enhancement

#91 Release
  src/3_widgets/support/ui/Support.tsx
Labels: release

#93 Code is split by Widgets #92
  src/1_app/ui/app/App.tsx
  src/3_widgets/results/api/GetPlaces.ts
Labels: enhancement

#94 Release
  src/1_app/ui/app/App.tsx
  src/3_widgets/results/api/GetPlaces.ts
Labels: release

#99 Added `app-ads.txt` file on root directory for iOS App. #98
  public/app-ads.txt
Labels: etc

#100 iOS App download badge is added on footer. #97
  index.html
  src/6_shared/ui/footer/Footer.tsx
  src/assets/images/appstore.svg
  tsconfig.app.json
  vite.config.ts
Labels: etc

#101 Release
  index.html
  public/app-ads.txt
  src/6_shared/ui/footer/Footer.tsx
  src/assets/images/appstore.svg
  tsconfig.app.json
  vite.config.ts
Labels: release

#102 Strings are changed #96
  src/3_widgets/report/ui/components/PageHeader.tsx
  src/3_widgets/report/ui/components/ReportButton.tsx
  src/3_widgets/report/ui/components/UploadButton.tsx
  src/6_shared/ui/errorAlert/ErrorAlert.tsx
  src/6_shared/ui/surchargeStatus/help/StatusHelp.tsx
Labels: enhancement

#104 Correcting endpoint #103
  src/3_widgets/report/api/postSurchargeInformation.ts
Labels: bug

#106 Release 1.0.0
  src/3_widgets/report/api/postSurchargeInformation.ts
  src/3_widgets/report/ui/components/PageHeader.tsx
  src/3_widgets/report/ui/components/ReportButton.tsx
  src/3_widgets/report/ui/components/UploadButton.tsx
  src/6_shared/ui/errorAlert/ErrorAlert.tsx
  src/6_shared/ui/surchargeStatus/help/StatusHelp.tsx
Labels: release

#107 Added ads.txt file #95
  public/ads.txt
Labels: enhancement

#108 Release
  public/ads.txt
Labels: release
