Repository Surcharges/Front-end, pull requests merged in 2025-01, with the labels that each got.

#30 Tooltip for surcharge report status has been added #29
  package.json
  src/3_widgets/detail/model/usePlaceViewModel.ts
  src/3_widgets/detail/ui/Detail.tsx
  src/3_widgets/detail/ui/components/map/GoogleMap.tsx
  src/3_widgets/detail/ui/components/surchargeInformation/SurchargesDetail.tsx
  src/3_widgets/detail/ui/components/surchargeInformation/status/help/StatusHelp.tsx
  src/3_widgets/results/model/usePlaceListViewModel.ts
  src/3_widgets/results/ui/Results.tsx
  src/3_widgets/results/ui/placelist/PlaceItem.tsx
  src/3_widgets/results/ui/placelist/PlaceList.tsx
  src/6_shared/model/firebase/Firebase.ts
  src/6_shared/model/index.ts
Labels: enhancement

#32 All `useParam` has been replaced by `useLocation` #31
  src/1_app/ui/app/App.tsx
  src/3_widgets/detail/ui/Detail.tsx
  src/3_widgets/report/ui/Report.tsx
  src/3_widgets/results/ui/Results.tsx
  src/4_features/searchBox/ui/SearchBox.tsx
Labels: enhancement

#36 Release Drafter has been configured #35
  .github/develop-drafter-config.yml
  .github/hotfix-drafter-config.yml
  .github/release-drafter-config.yml
  .github/workflows/develop-drafter.yml
  .github/workflows/hotfix-drafter.yml
  .github/workflows/release-drafter.yml
Labels: etc

#38 Lint has been corrected. #37
  src/3_widgets/detail/ui/Detail.tsx
Labels: etc

#39 env: `GitHub_Token` is added #35
  .github/workflows/develop-drafter.yml
  .github/workflows/hotfix-drafter.yml
  .github/workflows/release-drafter.yml
Labels: etc

#40 Secret has been added #35
  .github/workflows/develop-drafter.yml
  .github/workflows/hotfix-drafter.yml
  .github/workflows/release-drafter.yml
Labels: etc

#41 Drafter template has been changed #35
  .github/develop-drafter-config.yml
  .github/hotfix-drafter-config.yml
  .github/release-drafter-config.yml
Labels: etc

#48 reCAPTCHA v3 has been added #47
  src/3_widgets/detail/api/GetPlaceDetail.ts
  src/3_widgets/results/api/SearchPlaces.ts
  src/6_shared/model/firebase/Firebase.ts
  src/6_shared/model/makeAddress/MakeAddress.ts
Labels: etc

#50 Delete Major version draft. #49
  .github/develop-drafter-config.yml
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: etc

#53 Fixed refetching on mount. #33
  src/3_widgets/results/model/useGetPlacesQuery.ts
Labels: bug

#58 Added slack notification for build and deployment #54
  .github/workflows/release.yml
Labels: etc

#59 Surcharge rate information has been added on search list #1
  src/3_widgets/detail/model/usePlaceViewModel.ts
  src/3_widgets/detail/ui/Detail.tsx
  src/3_widgets/detail/ui/components/surchargeInformation/SurchargesDetail.tsx
  src/3_widgets/results/api/SearchPlaces.ts
  src/3_widgets/results/model/usePlaceListViewModel.ts
  src/3_widgets/results/ui/Results.tsx
  src/3_widgets/results/ui/placelist/PlaceItem.tsx
  src/5_entities/place/api/PlaceDTO.ts
  src/5_entities/place/model/PlaceModel.ts
  src/5_entities/place/ui/PlaceUI.ts
  src/5_entities/surcharges/api/SurchargesDTO.ts
  src/5_entities/surcharges/api/SurchargesStatusDTO.ts
  src/5_entities/surcharges/index.ts
  src/5_entities/surcharges/model/SurchargeModel.ts
  src/5_entities/surcharges/model/SurchargesModel.ts
  src/5_entities/surcharges/model/SurchargesStatusModel.ts
  src/5_entities/surcharges/ui/SurchargesStatusUI.ts
  src/5_entities/surcharges/ui/SurchargesUI.ts
  src/6_shared/ui/index.ts
  src/6_shared/ui/surchargeStatus/Confirmed.tsx
  src/6_shared/ui/surchargeStatus/Reported.tsx
  src/6_shared/ui/surchargeStatus/Unknown.tsx
  src/6_shared/ui/surchargeStatus/help/StatusHelp.tsx
Labels: feature

#61 Adjusted to server's new responses #60
  src/3_widgets/detail/api/GetPlaceDetail.ts
  src/3_widgets/report/api/DTO/PostSurchargeInformationRequest.ts
  src/3_widgets/report/api/postSurchargeInformation.ts
  src/3_widgets/report/model/usecases/UploadSurchargeInformation.ts
  src/3_widgets/report/model/viewmodels/useReportViewModel.ts
  src/3_widgets/results/api/SearchPlaces.ts
Labels: feature

#63 favicon has been added. #62
  LICENSE
  favicon.ico
  index.html
Labels: feature

#65 CI/CD setup have been changed. #64
  .github/develop-drafter-config.yml
  .github/hotfix-drafter-config.yml
Labels: etc

#67 Privacy Policy statement has been established. #66
  src/1_app/ui/app/App.tsx
  src/3_widgets/privacyPolicy/index.ts
  src/3_widgets/privacyPolicy/ui/PrivacyPolicy.tsx
Labels: enhancement

#73 FIxed dev-deployment script #71
  .github/workflows/dev-deployment.yml
Labels: etc

#74 Changed action scripts #71
  .github/workflows/dev-deployment.yml
  .github/workflows/prod-deployment.yml
Labels: etc

#76 Release
  .firebaserc
  .github/workflows/dev-deployment.yml
  .github/workflows/prod-deployment.yml
  package.json
  src/1_app/ui/app/App.tsx
  src/3_widgets/dashboard/index.ts
  src/3_widgets/dashboard/ui/DashBoard.tsx
  src/3_widgets/dashboard/ui/components/ConfirmationModal.tsx
  src/3_widgets/dashboard/ui/components/NavigationBar.tsx
  src/3_widgets/dashboard/ui/components/Search.tsx
  src/3_widgets/dashboard/ui/components/SurchargesList.tsx
  src/3_widgets/dashboard/ui/model/surcharge/Surcharge.ts
  src/3_widgets/detail/api/DTO/GetPlaceDetailResponse.ts
  src/3_widgets/detail/api/GetPlaceDetail.ts
  src/3_widgets/detail/model/usePlaceViewModel.ts
  src/3_widgets/login/index.ts
  src/3_widgets/login/ui/Login.tsx
  src/3_widgets/privacyPolicy/index.ts
  src/3_widgets/privacyPolicy/ui/PrivacyPolicy.tsx
  src/3_widgets/report/model/stores/usePlaceStore.ts
  src/3_widgets/results/api/DTO/GetPlacesResponse.ts
  src/3_widgets/results/api/GetPlaces.ts
  src/3_widgets/results/model/useGetPlacesQuery.ts
  src/3_widgets/results/model/usePlaceListViewModel.ts
  src/4_features/protected/index.ts
  src/4_features/protected/ui/Protected.tsx
  src/5_entities/result/index.ts
  src/5_entities/result/ui/PlaceListUI.ts
  src/5_entities/surcharges/api/SurchargesStatusDTO.ts
  src/6_shared/api/firebase/firebase.ts
  src/6_shared/api/index.ts
  src/6_shared/model/authContext/AuthContext.tsx
  src/6_shared/model/firebase/Firebase.ts
  src/6_shared/model/index.ts
Labels: release

#79 Personal information is changed #57
  src/6_shared/ui/footer/bonsung/Bonsung.tsx
Labels: enhancement

#80 ConfirmationModal updated to have a Bearer token in getImage request, header fixed #78
  src/3_widgets/dashboard/ui/components/ConfirmationModal.tsx
  src/3_widgets/dashboard/ui/components/SurchargesList.tsx
Labels: bug
